version: '3'
services:
  team1:
    image: simstest
    networks:
      static-network:
        ipv4_address: 172.20.1.1

  team2:
    image: simstest
    networks:
      static-network:
        ipv4_address: 172.20.2.1

  team3:
    image: simstest
    networks:
      static-network:
        ipv4_address: 172.20.3.1

  
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
    